import json

import pytest

import issue_bot as bot


@pytest.fixture
def state(tmp_path, monkeypatch):
    """Point the bot at throwaway state files and capture its replies."""
    monkeypatch.setattr(bot, "GUESTBOOK", tmp_path / "guestbook.json")
    monkeypatch.setattr(bot, "XO", tmp_path / "xo.json")
    monkeypatch.setattr(bot, "REPLY", tmp_path / "reply.json")
    return tmp_path


def issue(title, body="", user="alice", number=1):
    return {"title": title, "body": body, "user": {"login": user}, "number": number}


def reply(state):
    return json.loads((state / "reply.json").read_text(encoding="utf-8"))


# ---------------------------------------------------------------- sanitising
@pytest.mark.parametrize("raw, banned", [
    ("<script>alert(1)</script>", "<script>"),
    ("[click](http://evil.com)", "](http"),
    ("visit http://evil.com", "http://"),
    ("visit www.evil.com", "www.evil"),
    ("hi @octocat", "@octocat"),
    ("**bold** `code`", "**bold**"),
])
def test_clean_message_defuses_markup(raw, banned):
    assert banned not in bot.clean_message(f"### Message\n\n{raw}")


def test_clean_message_is_one_line_and_capped():
    out = bot.clean_message("### Message\n\n" + "line\n" * 10 + "x" * 500)
    assert "\n" not in out
    assert out.count("x") <= bot.MAX_MESSAGE


def test_clean_message_stops_at_footer_rule():
    body = "### Message\n\nhello there\n\n---\n_Generated by a tool_"
    assert bot.clean_message(body) == "hello there"


def test_clean_message_keeps_thai():
    assert "สวัสดีครับ" in bot.clean_message("### Message\n\nสวัสดีครับ")


# ---------------------------------------------------------------- guestbook
def test_guestbook_adds_entry_and_queues_reply(state):
    bot.handle_guestbook(issue("Guestbook", "### Message\n\nnice profile"))
    entries = json.loads((state / "guestbook.json").read_text(encoding="utf-8"))
    assert [e["message"] for e in entries] == ["nice profile"]
    assert reply(state)["completed"] is True


def test_guestbook_one_entry_per_day(state):
    bot.handle_guestbook(issue("Guestbook", "### Message\n\nfirst"))
    bot.handle_guestbook(issue("Guestbook", "### Message\n\nsecond", number=2))
    entries = json.loads((state / "guestbook.json").read_text(encoding="utf-8"))
    assert len(entries) == 1
    assert reply(state)["completed"] is False


def test_guestbook_rejects_empty(state):
    bot.handle_guestbook(issue("Guestbook", "### Message\n\n_No response_"))
    assert not (state / "guestbook.json").exists()
    assert reply(state)["completed"] is False


# ---------------------------------------------------------------- tic-tac-toe
@pytest.mark.parametrize("board, expected", [
    ("XXX      ", "X"),
    ("O  O  O  ", "O"),
    ("X   X   X", "X"),
    ("XOXXOOOXX", "draw"),
    ("X O      ", None),
])
def test_winner(board, expected):
    assert bot.winner(board) == expected


def test_bot_takes_the_win():
    assert bot.bot_move("OO XX    ") == 2


def test_bot_blocks():
    assert bot.bot_move("XX  O    ") == 2


def test_xo_move_is_saved_with_bot_reply(state):
    bot.handle_xo(issue("xo: 1"), 0)
    st = json.loads((state / "xo.json").read_text(encoding="utf-8"))
    assert st["board"][0] == "X"
    assert st["board"].count("O") == 1
    assert "You played **1**" in reply(state)["text"]


def test_xo_taken_square_changes_nothing(state):
    bot.handle_xo(issue("xo: 5"), 4)
    before = (state / "xo.json").read_text(encoding="utf-8")
    bot.handle_xo(issue("xo: 5", number=2), 4)
    assert (state / "xo.json").read_text(encoding="utf-8") == before
    assert reply(state)["completed"] is False


def test_finished_game_is_recorded_and_reset(state):
    bot.save(bot.XO, {"board": "XX OO    ", "stats": {"you": 0, "bot": 0, "draw": 0}, "log": []})
    bot.handle_xo(issue("xo: 3"), 2)
    st = json.loads((state / "xo.json").read_text(encoding="utf-8"))
    assert st["stats"]["you"] == 1
    assert st["board"] == " " * 9


def test_render_links_only_empty_squares(state):
    bot.save(bot.XO, {"board": "X   O    ", "stats": {"you": 0, "bot": 0, "draw": 0}, "log": []})
    html = bot.render_xo()
    assert html.count("issues/new?title=") == 7
